inventory:
  table:
    catalog: main
    database: default
    name: uc_migration_inventory

tacl:
  databases: [ "default" ]

warehouse_id: None

with_table_acls: False

groups:
  selected: [ "analyst" ]

num_threads: 80

