inventory:
  table:
    catalog: main
    database: default
    name: uc_migration_inventory


with_table_acls: False

groups:
  selected: [ "analyst" ]

num_threads: 80

rate_limit:
  max_requests_per_period: 10
  period_in_seconds: 1
