name: no-cheat

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    # required for merge queue to work. jobs.integration.if will mark it as skipped
    branches:
      - main

jobs:
  no-pylint-disable:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify no additional disabled lint in the new code
        run: |
          OLD_CODE=$(git diff origin/main..$(git branch --show-current) | grep -e '^-')
          OLD_CHEATS=$(echo "${OLD_CODE}" | grep -c '# pylint: disable'
          NEW_CODE=$(git diff origin/main..$(git branch --show-current) | grep -e '^+')
          NEW_CHEATS=$(echo "${NEW_CODE}" | grep -c '# pylint: disable'
          CHEATS=$((NEW_CHEATS-OLD_CHEATS))
          if [ "${CHEATS}" -ne 0 ]; then
            echo "Do not cheat the linter: ${CHEATS} new '# pylint: disable ...'"
            exit 1
          fi
