name: no-cheat

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    # required for merge queue to work. jobs.integration.if will mark it as skipped
    branches:
      - main

jobs:
  no-pylint-disable:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify no additional disabled lint in the new code
        run: |
          MAIN_CODE=$(git diff origin/main..$(git branch --show-current) | grep -e '^-')
          MAIN_CHEATS=$(echo "${MAIN_CODE}" | grep -c '# pylint: disable')
          BRANCH_CODE=$(git diff origin/main..$(git branch --show-current) | grep -e '^+')
          BRANCH_CHEATS=$(echo "${BRANCH_CODE}" | grep -c '# pylint: disable')
          NEW_CHEATS=$((BRANCH_CHEATS-MAIN_CHEATS))
          if [ "${NEW_CHEATS}" -gt 0 ]; then
            echo "Do not cheat the linter: ${NEW_CHEATS} new '# pylint: disable ...'"
            exit 1
          fi
