name: no-cheat

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    # required for merge queue to work. jobs.integration.if will mark it as skipped
    branches:
      - main

jobs:
  no-pylint-disable:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify no additional disabled lint in the new code
        run: |
          git diff origin/main..$(git branch --show-current) >> diff_data.txt
          RESULTS=$(python tests/unit/no_cheat.py diff_data.txt)
          if [ ${#RESULTS} -gt 0 ]; then
            echo ${RESULTS}
            exit 1
          fi
