name: solacc

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  solacc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: '3.10'

      - name: Install hatch
        run: pip install hatch==1.9.4

      - name: Verify linters on solution accelerators
        run: make solacc
