name: solacc

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

permissions:
  contents: read

jobs:
  solacc:
    runs-on:
      group: databrickslabs-protected-runner-group
      labels: linux-ubuntu-latest
    permissions:
      # Authenticate with JFrog for package resolution.
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
        with:
          version: "0.11.2"
          checksum: "7ac2ca0449c8d68dae9b99e635cd3bc9b22a4cb1de64b7c43716398447d42981"

      - name: Setup for JFrog
        uses: ./.github/actions/jfrog-auth

      - name: Verify linters on solution accelerators
        run: make solacc

      - name: Upload reports
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          name: report
          path: build/
          if-no-files-found: error
